import Head from 'next/head'
import '../styles/global.css'
export const metadata = {
  title: 'Nx Next App',
  description: 'Generated by create-nx-workspace'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <Head>
        <div>Hello</div>
      </Head>
      <body>{children}</body>
    </html>
  )
}
